#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# Create EKS cluster
eksctl create cluster \
  --name fin-loan-app \
  --version 1.35 \
  --region us-east-1 \
  --nodegroup-name workers \
  --node-type t3.medium \
  --nodes 2 \
  --nodes-min 2 \
  --nodes-max 4